{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ansible-ui.fullname" . }}-secrets
  labels:
    {{- include "ansible-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-secret: {{ .Values.appSecret | quote }}
  database-url: {{ include "ansible-ui.databaseURL" . | quote }}
  {{- if .Values.postgres.enabled }}
  postgres-password: {{ .Values.postgres.password | quote }}
  {{- end }}
  ldap-bind-password: {{ .Values.auth.ldap.bindPassword | quote }}
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
  github-client-secret: {{ .Values.auth.github.clientSecret | quote }}
  bitbucket-client-secret: {{ .Values.auth.bitbucket.clientSecret | quote }}
  radius-secret: {{ .Values.auth.radius.secret | quote }}
  tacacs-secret: {{ .Values.auth.tacacs.secret | quote }}
  saml-sp-key: {{ .Values.auth.saml.spKey | quote }}
{{- end }}
